### ISSUE TITLE
good-storage-roots/reg-extension-dir-root is not valid

### ISSUE THREAD

**Issue by srerickson** [zimeon/ocfl-py#102]
One of the fixtures, `good-storage-roots/reg-extension-dir-root`, is not valid as expected because the storage layout doesn't conform with the declared extension.

- the sha256 of the object id `ark:123/abc` is `a4781783dcec...` not `b02c71b67afe...`
- the [declared layout extension](https://github.com/OCFL/extensions/blob/main/docs/0003-hash-and-id-n-tuple-storage-layout.md) requires lowercase hex strings but uppercase are used.

I think the correct storage location for `ark:123/abc` is `a47/817/83d/cec/ark%3a123%2fabc`

**Comment by zimeon** [comment]
Thank you @srerickson ! I agree on both counts.

I think I got this digest wrong because I did:
```
> echo "ark:123/abc" | shasum -a 256
b02c71b67afeeb7adcf12259e94f909bdc9c95e29c9f180f466e10a96420f6f4  -
```
when I should have done:
```
> echo -n "ark:123/abc" | shasum -a 256
a4781783dceceffe7af9af3fc4299cc6c93dc87754d6353d31a9e44e8a2838a0  -
```
or
```
> python -c 'import hashlib; print(hashlib.sha256(b"ark:123/abc").hexdigest())'
a4781783dceceffe7af9af3fc4299cc6c93dc87754d6353d31a9e44e8a2838a0
```

**Comment by zimeon** [comment]
Example file dir and name fixed but I note there isn't yet code in `ocfl/store.py` so that `ocfl-validate.py` will check any of this
