### ISSUE TITLE
Question: how do I add a new version of a content file to an existing object?

### ISSUE THREAD

**Issue by bcail** [zimeon/ocfl-py#5]
If I have an existing object, and now I want to add a new version of a content file, what method do I call? Seems like Object.add_version expects a fully-created ocfl version directory, but I just want to add a new content file, without building a new ocfl version. Or do I have to create a new ocfl version first, and then add it to the object?

Thanks.

**Comment by bcail** [comment]
I guess I'm looking for the functionality that's in [Birkland's ocfl client](https://github.com/birkland/ocfl):

> Copy some more stuff into the object (creating another version)
> 
>     ocfl cp /etc/hosts test:stuff

**Comment by zimeon** [comment]
I haven't imagined the case of adding a single file use in what is written so far. I have only considered adding whole versions to an object (which is then managed with `Object.add_version` as you note)

**Comment by bcail** [comment]
@zimeon would you be open to a PR that lets you add just one file (or multiple files) to an object, without constructing a full version directory?

**Comment by bcail** [comment]
I'd like to be able to do something like this:
```
with open(...) as f:
    write_file_to_object(object_id=test:1, file_obj=f, path=file1.txt)
```
So all I have to know is the file that I'm adding, and the object id. Would that make sense to add?

**Comment by zimeon** [comment]
I don't think I would want to add facilities to update an already written version because that doesn't follow the archival model of OCFL. I think it would be interesting to have a facility that added/removed/updated files starting from the current version, **while creating a new version**

**Comment by bcail** [comment]
sorry, yes, that's what I mean - create a new version (but having all the versioning, existing files, ... hidden where the user doesn't have to know about it)

**Comment by bcail** [comment]
ocfl-java has the idea of updating an object with a series of actions that result in a new version in the object:
https://github.com/UW-Madison-Library/ocfl-java/blob/master/ocfl-java-api/src/main/java/edu/wisc/library/ocfl/api/OcflObjectUpdater.java

So the user can add files, remove files, ... and a new version gets created with the results of those actions.

Should we do something similar here in this package? We could have actions that can be taken on an Object, and then a commit method, or a new object updater class that handles the actions and gets passed to an update_object method like ocfl-java does, ...

Any thoughts on the approach you'd like to see?

**Comment by zimeon** [comment]
Yes, I think a file-by-file updater to create a new version would be good. If we were cute it could be a context manager so one could do something like:

```
with ocfl_obj.new_version() as nv:
    nv.add_file(..)
    nv.rename_file(...)
    nv.delete_file(...)
    ...
```

where successful completion writes the new version and updates the inventory etc., an exception tidies up the incomplete new version creation

**Comment by zimeon** [comment]
Has been implemented in https://github.com/zimeon/ocfl-py/blob/main/ocfl/new_version.py 

```
        >>> # Prep:
        >>> # mkdir tmp
        >>> # cp -rp fixtures/1.1/good-objects/spec-ex-full tmp/spec-ex-full
        >>>
        >>> import ocfl
        >>> object = ocfl.Object()
        >>> nv = object.start_new_version(objdir="tmp/spec-ex-full", carry_content_forward=True)
        >>> nv.inventory.current_version.logical_paths
        ['foo/bar.xml', 'empty2.txt', 'image.tiff']
        >>> nv.delete("foo/bar.xml")
        >>> nv.rename("empty2.txt", "empty3.txt")
        >>> nv.add("fixtures/1.1/content/README.md", "readme", "v4/readme")
        >>> object.write_new_version(nv)
        INFO:root:Updated OCFL object ark:/12345/bcd987 in tmp/spec-ex-full by adding v4
        <ocfl.inventory.Inventory object at 0x1014e6cd0>
```
