### ISSUE TITLE
Storage Root `extensions/` directory flagged as validation error

### ISSUE THREAD

**Issue by awoods** [zimeon/ocfl-py#76]
When using a custom storage layout extension, the configuration of the extension is placed in the storage root as:
`[storage-root]/extensions/NNNN-flat-omit-prefix-storage-layout/config.json`

The ocfl-validate utility flags this as an error:
```
[E072] OCFL storage root hierarchy include directory /extensions/NNNN-flat-omit-prefix-storage-layout with at least one file but no object declaration. Such additional files are not allowed (see https://ocfl.io/1.0/spec/#E072)
```

Per the spec, I believe this should be valid.
See: https://ocfl.io/1.0/spec/#storage-root-extensions

**Comment by zimeon** [comment]
Agree that this is a bug -- there simply isn't code to handle extensions directories in storage roots at present, will fix

I also note that while the spec https://ocfl.io/1.0/spec/#storage-root-extensions is clear that an error in the storage root extensions structure should result in [E086](https://ocfl.io/1.0/spec/#E086), there is no warning code defined for use of an unregistered extension in a storage root. The code [W013](https://ocfl.io/1.0/spec/#W013) is used in object roots. I will use a local code for now (`W901`) and file a spec issue

**Comment by zimeon** [comment]
--> https://github.com/OCFL/spec/issues/557
